version: 2

sources:
  - name: gz_raw_data
    description: raw data
    tables:
      - name: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        columns:
           - name: date_date
             description: date of purchase
           - name: orders_id
             description: order id
           - name: product_id
             description: product id
           - name: revenue
             description: revenue per order
           - name: quantity
             description: qty per order  
      - name: raw_gz_product
        description: products of Greenweez / we have on row per product_price found in each product_id
        columns: 
          - name: products_id
            description: Primary key
          - name: purchase_price 
            description: purchase price per product
      - name: raw_gz_ship
        description: shipping of Greenweez / we have on row per ship_log_price found in each order_id
        columns:
           - name: orders_id
             description: Primary key
           - name: shipping_fee
             description: shipping fee per order
           - name: log_cost
             description: log_cost
           - name: ship_cost
             description: ship cost
models:
   - name: int_sales_margin
     description: margin calculation per order
     columns:
       - name: orders_id
         description: orders key
         tests:
           - not_null
       - name: products_id
         description: products key
         tests:
           - not_null
       - name: margin
         description: Margin = Revenue - Purchase_cost
         tests:
           - not_null
       - name: Purchase_cost
         description: Purchase_cost = Quantity * Purchase_price
         tests:
           - not_null
       - name: date_date
         description: date of the order
         tests:
           - not_null
       - name: revenue
         description: sum of revenue per order
         tests:
           - not_null
       - name: quantity
         description: sum of quantity per order
         tests:
           - not_null
     tests:
       - unique:
           column_name: "(orders_id || '-' || products_id)"

models:
  - name: int_orders_margin
    description: margin calculation per order
    columns:
       - name: orders_id
         description: orders key
         tests:
           - not_null
       - name: date_date
         description: date of order
         tests:
           - not_null
       - name: revenue
         description: sum of revenue per order
         tests:
           - not_null
       - name: quantity
         description: sum of quantity per order
         tests:
           - not_null
       - name: Purchase_cost
         description: Purchase_cost = Quantity * Purchase_price
         tests:
           - not_null
       - name: margin
         description: Margin = Revenue - Purchase_cost
         tests:
           - not_null
    tests:
       - unique:
           column_name: "(orders_id || '-' || products_id)"
models:
  - name: int_orders_operational
    description: operational calculation per order
    columns:
       - name: orders_id
         description: orders key
         tests:
           - not_null
       - name: date_date
         description: date of order
         tests:
           - not_null
       - name: operational_margin
         description: operational calculation
         tests:
          - not_null
       - name: quantity
         description: sum of quantity per order
         tests:
           - not_null
       - name: revenue
         description: sum of revenue per order
         tests:
           - not_null
       - name: purchase_cost
         description: purchase_cost = Quantity * Purchase_price
         tests:
           - not_null
       - name: margin
         description: margin = revenue - purchase_cost
         tests:
           - not_null
       - name: shipping_fee
         description: shipping fee
         tests:
          - not_null
       - name: log_cost
         description: logcost
         tests:
          - not_null
       - name: ship_cost
         description: ship cost
         tests:
          - not_null
    tests:
       - unique:
           column_name: "(orders_id || '-' || ship_cost)"
